### ISSUE TITLE
How to create roles and how can I assign them?

### ISSUE THREAD

**Issue by xXFireBlastXx** [Cvolton/GMDprivateServer#118]
I have seen that now you can create roles and assign people, but are they created automatically or manually? Help me Pls, I also want to know how the text changes color and add the symbol of elder and normal moderators.

**Comment by AnubisTDG** [comment]
You create them manually, just go to the _roles_ table and go to the top and click "insert". you should see a bunch of stuff to fill out. Leave _role ID_ blank and for the rest write 1 if you want to grant a permission or 0 to deny it. For role color, insert an RGB code (https://www.w3schools.com/colors/colors_rgb.asp). Not really sure what "priority" is. As for assigning them, just go to the _roleassign_ table and click "insert" again. You can leave assignID blank and copy/past the role ID and your account ID into the correct places. 

I'm pretty sure thats how it works, but the system is really buggy tbh (for me anyways) but I'm pretty sure thats how it works but feel free to correct me if I'm wrong. Hopefully this helps. :)

**Comment by xXFireBlastXx** [comment]
Thanks for the help, but they do not load me the texts of colors, the rolls if they appear in the list "Vip" but the texts do not appear of colors. :(

**Comment by Cvolton** [comment]
with the most recent version of the gdps source, modBadgeLevel and actionRequestMod accept values 0-2 (0=not a mod, 1=normal mod, 2=elder mod) and modBadgeLevel must be at least 1 for colored comments to work. 

Also I recommend creating a normal user role that has isDefault set to 1 (leave it at 0 for all other roles, otherwise the GDPS might get confused and could make all people mods)

Also priority exists because you can assign multiple roles to 1 person, the GDPS always goes from the top to the bottom when checking permissions - setting a permission to 0 means "check if a lower priority role has the permission and if the user requesting it has that lower priority role"

I hope I didn't make this explaination too confusing. I plan to make a role manager in the dashboard later on, but I'm currently focusing on updating the GDPS to 2.11 and getting the system to actually work, since commands for example still depend on the old isAdmin variable

**Comment by xXFireBlastXx** [comment]
Ok, I understand, but what I do not understand is where I find the modBadgeLevel and actionRequestMod, where are you supposed to be? in the database?, and if it would be there, how do I add it?

**Comment by DonAlex0** [comment]
actionRequestMod is on the roles tab in the database, but I didn't find modBadgeLevel anywhere

**Comment by Cvolton** [comment]
modBadgeLevel is supposed to be in the roles tab too, however I didn't commit the latest database.sql at the time you downloaded the repository yet, it's fixed in the latest one, what I recommend you to do for a quick fix is that you just create a type INT column called "modBadgeLevel" in the "roles" table (you can do that in the "structure" tab in phpMyAdmin), this should also solve the comments issue that people have

**Comment by xXFireBlastXx** [comment]
I appreciate all your help, it still does not work for me (I do not know why), but now I miss an error in the weekly demon, the bug is when I enter my account, charge data and I want to play the weekly, it does not load me, but when I log out I load the weekly.

**Comment by xXFireBlastXx** [comment]
Well, I found the problem, I already get the colored texts! Thanks Cvolton and AnubisTDG!  I'm going to close the section

**Comment by EMREOYUN** [comment]
How to create roles table?

**Comment by EMREOYUN** [comment]
i didnt have roles table
