### ISSUE TITLE
ip-ban doesn't work

### ISSUE THREAD

**Issue by NightDust12** [Cvolton/GMDprivateServer#903]
Please fix ip-ban not working. I tried banning someone that wasn't following the rules in my server and ip-ban does nothing. That person can still make account, make levels, etc. Please fix this.

**Comment by MegaSa1nt** [comment]
i think ip-ban is unused

**Comment by MegaSa1nt** [comment]
hey, @NightDust12! i fixed that, check #905

**Comment by NightDust12** [comment]
it still does nothing. I tested myself by banning my self (My ip) on my gdps and i could still do everything that i could do when i wasn't banned.

**Comment by MegaSa1nt** [comment]
> it still does nothing. I tested myself by banning my self (My ip) on my gdps and i could still do everything that i could do when i wasn't banned.

lol it works fine for me, try changing $_SERVER["REMOTE_ADDR"] to $_SERVER['HTTP_CF_CONNECTING_IP'] or $_SERVER['HTTP_X_FORWARDED_FOR'] on line 10

**Comment by MegaSa1nt** [comment]
hey! i updated my ban fix PR! Check it!
